import Testing
import Foundation
import OmFileFormatC

/// Wire-format fixtures, pinned after the 64-bit SIMD lane-order fix.
/// Encoders must write zero unused tail bits; historical nonzero padding is
/// retained separately below as decode-only compatibility fixtures.
/// Expected bytes are literals, never generated by a codec during tests.
/// Do not refresh them merely to make a failure pass: investigate compatibility
/// first. These fixtures cover selected encodings, not every possible stream.
@Suite struct CompressedBytesCompatibilityTests {
    enum Codec: Int, Sendable { case delta, zigzag, pfor, pforSIMD, fpx }
    enum Pattern: Sendable {
        case tail, blocksAndTail, exceptions, seedOrConstant, zeros
        case boundary, packedWidth(Int), literal([UInt64])
        case wraparound, exceptionEdges, denseExceptions, floatEdges
    }

    struct Fixture: Sendable, CustomTestStringConvertible {
        let bits: Int
        let codec: Codec
        let pattern: Pattern
        let count: Int
        let hex: String
        var label: String = ""
        var testDescription: String { "\(codec)\(bits)/\(label.isEmpty ? String(describing: pattern) : label)/n=\(count)" }

        // Values for FPX are IEEE bit patterns so signed zero and NaN payloads
        // are compared exactly, without floating-point equality or arithmetic.
        var values: [UInt64] {
            if case .literal(let values) = pattern {
                precondition(values.count == count)
                return values
            }
            let mask = UInt64.max >> (64 - bits)
            var v: UInt64 = 0
            return (0..<count).map { i in
                switch pattern {
                case .tail:
                    v = codec == .zigzag
                        ? UInt64(10 + (i % 2 == 1 ? (i + 1) / 2 : -i / 2))
                        : UInt64(10 + i * (i + 1) / 2)
                case .blocksAndTail:
                    v = codec == .delta ? v + UInt64(i % 7) : UInt64(i % 8)
                case .exceptions:
                    if codec == .fpx {
                        let floatBits: [UInt64] = [0, 0x80000000, 0x3f800000, 0x3fc00000,
                                                   0xc0000000, 0x7f800000, 0xff800000, 0x7fc12345]
                        let doubleBits: [UInt64] = [0, 0x8000000000000000, 0x3ff0000000000000, 0x3ff8000000000000,
                                                    0xc000000000000000, 0x7ff0000000000000, 0xfff0000000000000, 0x7ff8123456789abc]
                        v = bits == 32 ? floatBits[i] : doubleBits[i]
                    } else if codec == .delta || codec == .zigzag {
                        v += i == 64 ? UInt64(1) << (bits - 2) : 1
                    } else {
                        v = i == 64 ? UInt64(1) << (bits - 2) : UInt64(i % 4)
                    }
                case .seedOrConstant: v = mask
                case .zeros: v = 0
                case .boundary: v = UInt64(codec == .delta ? i / 3 : i % 5)
                case .packedWidth(let width):
                    v = ((UInt64(i) &* 0x9e3779b97f4a7c15) ^ 0xd1b54a32d192ed03) & (UInt64.max >> (64 - width))
                case .wraparound: v = (mask - 2) &+ UInt64(i * 3)
                case .exceptionEdges, .denseExceptions:
                    let predicted = codec == .delta || codec == .zigzag
                    if predicted && i == 0 {
                        v = mask - 2
                        break
                    }
                    let j = predicted ? i - 1 : i
                    let exceptional: Bool
                    if case .exceptionEdges = pattern {
                        exceptional = [0, 1, 62, 63, 64, 65, 126, 127].contains(j)
                    } else {
                        exceptional = j % 3 == 0
                    }
                    let step = exceptional ? UInt64(1) << (bits - 2) : UInt64(j % 4)
                    v = predicted ? (v &+ step) & mask : step
                case .floatEdges:
                    let floatBits: [UInt64] = [0, 0x80000000, 1, 0x80000001, 0x007fffff, 0x00800000,
                        0x3f800000, 0xbf800000, 0x7f7fffff, 0xff7fffff, 0x7f800000, 0xff800000,
                        0x7fc00001, 0x7fc12345, 0xffc54321, 0x7f800001]
                    let doubleBits: [UInt64] = [0, 0x8000000000000000, 1, 0x8000000000000001,
                        0x000fffffffffffff, 0x0010000000000000, 0x3ff0000000000000, 0xbff0000000000000,
                        0x7fefffffffffffff, 0xffefffffffffffff, 0x7ff0000000000000, 0xfff0000000000000,
                        0x7ff8000000000001, 0x7ff8123456789abc, 0xfff8abcdef012345, 0x7ff0000000000001]
                    v = bits == 32 ? floatBits[i % floatBits.count] : doubleBits[i % doubleBits.count]
                case .literal: preconditionFailure("Handled before building values")
                }
                return v & mask
            }
        }

        var compressed: [UInt8] {
            let chars = Array(hex.filter { !$0.isWhitespace }.utf8)
            precondition(chars.count % 2 == 0)
            func nibble(_ c: UInt8) -> UInt8 {
                precondition((48...57).contains(c) || (97...102).contains(c))
                return c <= 57 ? c - 48 : c - 97 + 10
            }
            return stride(from: 0, to: chars.count, by: 2).map { nibble(chars[$0]) << 4 | nibble(chars[$0 + 1]) }
        }
    }

    static let fixtures: [Fixture] = [
        Fixture(bits: 8, codec: .delta, pattern: .tail, count: 9, hex: "0a0421436587"),
        Fixture(bits: 8, codec: .delta, pattern: .blocksAndTail, count: 137, hex: "0003d158231a6b44638d68ac118d35a2b14634d688c61ad158231a6b44638d68ac118d35a2b14634d688c61ad158231a6b4403638d68"),
        Fixture(bits: 8, codec: .delta, pattern: .exceptions, count: 129, hex: "0181060000000000000080000000000000000020ffffffffffffff7fffffffffffffffff"),
        Fixture(bits: 8, codec: .delta, pattern: .seedOrConstant, count: 1, hex: "ff"),
        Fixture(bits: 8, codec: .zigzag, pattern: .tail, count: 9, hex: "0a043276bafe"),
        Fixture(bits: 8, codec: .zigzag, pattern: .blocksAndTail, count: 137, hex: "00820280808080808080808080808080808080ffffffffaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6a04222222d2"),
        Fixture(bits: 8, codec: .zigzag, pattern: .exceptions, count: 129, hex: "0182060000000000000080000000000000000020aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
        Fixture(bits: 8, codec: .zigzag, pattern: .seedOrConstant, count: 1, hex: "ff"),
        Fixture(bits: 8, codec: .pfor, pattern: .blocksAndTail, count: 128, hex: "0388c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa"),
        Fixture(bits: 8, codec: .pfor, pattern: .exceptions, count: 128, hex: "82050000000000000000010000000000000010e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4"),
        Fixture(bits: 8, codec: .pfor, pattern: .seedOrConstant, count: 8, hex: "c8ff"),
        Fixture(bits: 16, codec: .delta, pattern: .tail, count: 9, hex: "0a0421436587"),
        Fixture(bits: 16, codec: .delta, pattern: .blocksAndTail, count: 137, hex: "0003d1581a6b638dac1135a2463488c6d158231a446368ac8d35b146d6881ad1231a6b448d68118da2b134d6c61a58236b4403638d68"),
        Fixture(bits: 16, codec: .delta, pattern: .exceptions, count: 129, hex: "014101ffffffffffffffffffffffffffff7fffd04f3f"),
        Fixture(bits: 16, codec: .delta, pattern: .seedOrConstant, count: 1, hex: "c0ffff"),
        Fixture(bits: 16, codec: .zigzag, pattern: .tail, count: 9, hex: "0a043276bafe"),
        Fixture(bits: 16, codec: .zigzag, pattern: .blocksAndTail, count: 137, hex: "00820280808080808080808080808080808080ffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaa5555aaaaaaaaaaaaaaaaaaaaaaaaaaaa555504222222d2"),
        Fixture(bits: 16, codec: .zigzag, pattern: .exceptions, count: 129, hex: "014201aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad04f3f"),
        Fixture(bits: 16, codec: .zigzag, pattern: .seedOrConstant, count: 1, hex: "c0ffff"),
        Fixture(bits: 16, codec: .pfor, pattern: .blocksAndTail, count: 128, hex: "0388c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa"),
        Fixture(bits: 16, codec: .pfor, pattern: .exceptions, count: 128, hex: "4201e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4c04f40"),
        Fixture(bits: 16, codec: .pfor, pattern: .seedOrConstant, count: 8, hex: "d0ffff"),
        Fixture(bits: 16, codec: .pforSIMD, pattern: .blocksAndTail, count: 128, hex: "03000049929224dbb624496ddbb66dffff0000244949926ddb9224b66ddbb6ffff000092242449b66d4992dbb66ddbffff"),
        Fixture(bits: 16, codec: .pforSIMD, pattern: .exceptions, count: 128, hex: "420100005555aaaaffff00005555aaaaffff00005555aaaaffff00005555aaaaffffc04f40"),
        Fixture(bits: 16, codec: .pforSIMD, pattern: .seedOrConstant, count: 8, hex: "d0ffff"),
        Fixture(bits: 32, codec: .delta, pattern: .tail, count: 9, hex: "0a0421436587"),
        Fixture(bits: 32, codec: .delta, pattern: .blocksAndTail, count: 137, hex: "0003a93c3095f2c0541e035379604ce581a907a6f2c098ca03532a0f4ce53c309507541e98ca79602a0f81a93c30a6f2c05403638d68"),
        Fixture(bits: 32, codec: .delta, pattern: .exceptions, count: 129, hex: "014101ffffffffffffffffffffffffff7fffffff000000203f"),
        Fixture(bits: 32, codec: .delta, pattern: .seedOrConstant, count: 1, hex: "f0ffffffff"),
        Fixture(bits: 32, codec: .zigzag, pattern: .tail, count: 9, hex: "0a043276bafe"),
        Fixture(bits: 32, codec: .zigzag, pattern: .blocksAndTail, count: 137, hex: "00820280808080808080808080808080808080ffffffffaaaaaaaaaaaaaaaaaaaaaaaa66666666aaaaaaaaaaaaaaaaaaaaaaaa6666666604222222d2"),
        Fixture(bits: 32, codec: .zigzag, pattern: .exceptions, count: 129, hex: "014201aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff000000203f"),
        Fixture(bits: 32, codec: .zigzag, pattern: .seedOrConstant, count: 1, hex: "f0ffffffff"),
        Fixture(bits: 32, codec: .pfor, pattern: .blocksAndTail, count: 128, hex: "0388c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa"),
        Fixture(bits: 32, codec: .pfor, pattern: .exceptions, count: 128, hex: "4201e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4ff0000001040"),
        Fixture(bits: 32, codec: .pfor, pattern: .seedOrConstant, count: 8, hex: "e0ffffffff"),
        Fixture(bits: 32, codec: .pforSIMD, pattern: .blocksAndTail, count: 128, hex: "0320088220699aa669b22ccbb2fbbeeffb088220089aa6699a2ccbb22cbeeffbbe82200882a6699aa6cbb22ccbeffbbeef"),
        Fixture(bits: 32, codec: .pforSIMD, pattern: .exceptions, count: 128, hex: "42010000000055555555aaaaaaaaffffffff0000000055555555aaaaaaaaffffffffff0000001040"),
        Fixture(bits: 32, codec: .pforSIMD, pattern: .seedOrConstant, count: 8, hex: "e0ffffffff"),
        Fixture(bits: 32, codec: .fpx, pattern: .tail, count: 9, hex: "1a061488b9088b9d04"),
        Fixture(bits: 32, codec: .fpx, pattern: .blocksAndTail, count: 137, hex: "1d03f8ffffff24499224b66ddbb624499224ffffffff499224496ddbb66d49922449ffffffff92244992dbb66ddb922449921d03a7799a07"),
        Fixture(bits: 32, codec: .fpx, pattern: .exceptions, count: 8, hex: "008a168020b1280004d01f80fff7174080"),
        Fixture(bits: 32, codec: .fpx, pattern: .seedOrConstant, count: 1, hex: "00e0ffffffff"),
        Fixture(bits: 64, codec: .delta, pattern: .tail, count: 9, hex: "0a0421436587"),
        Fixture(bits: 64, codec: .delta, pattern: .blocksAndTail, count: 137, hex: "0003d158231a6b44638d68ac118d35a2b14634d688c61ad158231a6b44638d68ac118d35a2b14634d688c61ad158231a6b4403638d68"),
        Fixture(bits: 64, codec: .delta, pattern: .exceptions, count: 129, hex: "014101ffffffffffffff7fffffffffffffffffff00000000000000203f"),
        Fixture(bits: 64, codec: .delta, pattern: .seedOrConstant, count: 1, hex: "ffffffffffffffffff"),
        Fixture(bits: 64, codec: .zigzag, pattern: .tail, count: 9, hex: "0a043276bafe"),
        Fixture(bits: 64, codec: .zigzag, pattern: .blocksAndTail, count: 137, hex: "00820280808080808080808080808080808080ffffffffaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6aaa6a04222222d2"),
        Fixture(bits: 64, codec: .zigzag, pattern: .exceptions, count: 129, hex: "014201aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff00000000000000203f"),
        Fixture(bits: 64, codec: .zigzag, pattern: .seedOrConstant, count: 1, hex: "ffffffffffffffffff"),
        Fixture(bits: 64, codec: .pfor, pattern: .blocksAndTail, count: 128, hex: "0388c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa88c6fa"),
        Fixture(bits: 64, codec: .pfor, pattern: .exceptions, count: 128, hex: "4201e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4ff000000000000001040"),
        Fixture(bits: 64, codec: .pfor, pattern: .seedOrConstant, count: 8, hex: "ffffffffffffffffff"),
        Fixture(bits: 64, codec: .pforSIMD, pattern: .blocksAndTail, count: 128, hex: "0320088220699aa669b22ccbb2fbbeeffb088220089aa6699a2ccbb22cbeeffbbe82200882a6699aa6cbb22ccbeffbbeef"),
        Fixture(bits: 64, codec: .pforSIMD, pattern: .exceptions, count: 128, hex: "42010000000055555555aaaaaaaaffffffff0000000055555555aaaaaaaaffffffffff000000000000001040"),
        Fixture(bits: 64, codec: .pforSIMD, pattern: .seedOrConstant, count: 8, hex: "ffffffffffffffffff"),
        Fixture(bits: 64, codec: .fpx, pattern: .tail, count: 9, hex: "3a061488b9088b9d04"),
        Fixture(bits: 64, codec: .fpx, pattern: .blocksAndTail, count: 137, hex: "3d03f8ffffff24499224b66ddbb624499224ffffffff499224496ddbb66d49922449ffffffff92244992dbb66ddb922449923d03a7799a07"),
        Fixture(bits: 64, codec: .fpx, pattern: .exceptions, count: 8, hex: "008e308020b1a87964f5004000d0ff0040ff5fff13000440"),
        Fixture(bits: 64, codec: .fpx, pattern: .seedOrConstant, count: 1, hex: "00ffffffffffffffffff"),
        Fixture(bits: 8, codec: .delta, pattern: .zeros, count: 137, hex: "000000"),
        Fixture(bits: 8, codec: .zigzag, pattern: .zeros, count: 137, hex: "000000"),
        Fixture(bits: 8, codec: .pfor, pattern: .zeros, count: 128, hex: "00"),
        Fixture(bits: 16, codec: .delta, pattern: .zeros, count: 137, hex: "000000"),
        Fixture(bits: 16, codec: .zigzag, pattern: .zeros, count: 137, hex: "000000"),
        Fixture(bits: 16, codec: .pfor, pattern: .zeros, count: 128, hex: "00"),
        Fixture(bits: 16, codec: .pforSIMD, pattern: .zeros, count: 128, hex: "00"),
        Fixture(bits: 32, codec: .delta, pattern: .zeros, count: 137, hex: "000000"),
        Fixture(bits: 32, codec: .zigzag, pattern: .zeros, count: 137, hex: "000000"),
        Fixture(bits: 32, codec: .pfor, pattern: .zeros, count: 128, hex: "00"),
        Fixture(bits: 32, codec: .pforSIMD, pattern: .zeros, count: 128, hex: "00"),
        Fixture(bits: 32, codec: .fpx, pattern: .zeros, count: 136, hex: "20002000"),
        Fixture(bits: 64, codec: .delta, pattern: .zeros, count: 137, hex: "000000"),
        Fixture(bits: 64, codec: .zigzag, pattern: .zeros, count: 137, hex: "000000"),
        Fixture(bits: 64, codec: .pfor, pattern: .zeros, count: 128, hex: "00"),
        Fixture(bits: 64, codec: .pforSIMD, pattern: .zeros, count: 128, hex: "00"),
        Fixture(bits: 64, codec: .fpx, pattern: .zeros, count: 136, hex: "40004000"),
    ]

    // These previously emitted streams contain nonzero unused bits. Keep
    // decoding them, but never require the encoder to reproduce scratch data.
    static let legacyPaddingFixtures: [Fixture] = [
        Fixture(bits: 8, codec: .delta, pattern: .exceptions, count: 129, hex: "01810600000000000000800000000000000000e0ffffffffffffff7fffffffffffffffff"),
        Fixture(bits: 8, codec: .pfor, pattern: .exceptions, count: 128, hex: "820500000000000000000100000000000000d0e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4"),
        Fixture(bits: 32, codec: .fpx, pattern: .blocksAndTail, count: 137, hex: "1d03f8ffffff24499224b66ddbb624499224ffffffff499224496ddbb66d49922449ffffffff92244992dbb66ddb922449921d03a7799a67"),
        Fixture(bits: 64, codec: .fpx, pattern: .blocksAndTail, count: 137, hex: "3d03f8ffffff24499224b66ddbb624499224ffffffff499224496ddbb66d49922449ffffffff92244992dbb66ddb922449923d03a7799a3f"),
    ]

    @Test(arguments: legacyPaddingFixtures)
    func decodingHistoricalPadding(_ f: Fixture) {
        decodingFixedBytes(f)
    }

    // TurboPFor's original entry points require caller padding. Use aligned
    // storage for typed C accesses, with deterministic padding outside the data.
    private func valueBytes(_ f: Fixture) -> [UInt8] {
        f.values.flatMap { value -> [UInt8] in
            var littleEndian = value.littleEndian
            return withUnsafeBytes(of: &littleEndian) { Array($0.prefix(f.bits / 8)) }
        }
    }

    private func encode(_ f: Fixture, _ input: UnsafeMutableRawPointer, _ output: UnsafeMutablePointer<UInt8>) -> Int {
        switch (f.bits, f.codec) {
        case (8, .delta): return p4ndenc8(input.assumingMemoryBound(to: UInt8.self), f.count, output)
        case (8, .zigzag): return p4nzenc8(input.assumingMemoryBound(to: UInt8.self), f.count, output)
        case (8, .pfor): return p4nenc8(input.assumingMemoryBound(to: UInt8.self), f.count, output)
        case (16, .delta): return p4ndenc128v16(input.assumingMemoryBound(to: UInt16.self), f.count, output)
        case (16, .zigzag): return p4nzenc128v16(input.assumingMemoryBound(to: UInt16.self), f.count, output)
        case (16, .pfor): return p4nenc16(input.assumingMemoryBound(to: UInt16.self), f.count, output)
        case (16, .pforSIMD): return p4nenc128v16(input.assumingMemoryBound(to: UInt16.self), f.count, output)
        case (32, .delta): return p4ndenc128v32(input.assumingMemoryBound(to: UInt32.self), f.count, output)
        case (32, .zigzag): return p4nzenc128v32(input.assumingMemoryBound(to: UInt32.self), f.count, output)
        case (32, .pfor): return p4nenc32(input.assumingMemoryBound(to: UInt32.self), f.count, output)
        case (32, .pforSIMD): return p4nenc128v32(input.assumingMemoryBound(to: UInt32.self), f.count, output)
        case (32, .fpx): return fpxenc32(input.assumingMemoryBound(to: UInt32.self), f.count, output, 0)
        case (64, .delta): return p4ndenc64(input.assumingMemoryBound(to: UInt64.self), f.count, output)
        case (64, .zigzag): return p4nzenc64(input.assumingMemoryBound(to: UInt64.self), f.count, output)
        case (64, .pfor): return p4nenc64(input.assumingMemoryBound(to: UInt64.self), f.count, output)
        case (64, .pforSIMD): return p4nenc128v64(input.assumingMemoryBound(to: UInt64.self), f.count, output)
        case (64, .fpx): return fpxenc64(input.assumingMemoryBound(to: UInt64.self), f.count, output, 0)
        default: preconditionFailure("Unsupported fixture codec")
        }
    }

    private func decode(_ f: Fixture, _ input: UnsafeMutablePointer<UInt8>, _ output: UnsafeMutableRawPointer) -> Int {
        switch (f.bits, f.codec) {
        case (8, .delta): return p4nddec8(input, f.count, output.assumingMemoryBound(to: UInt8.self))
        case (8, .zigzag): return p4nzdec8(input, f.count, output.assumingMemoryBound(to: UInt8.self))
        case (8, .pfor): return p4ndec8(input, f.count, output.assumingMemoryBound(to: UInt8.self))
        case (16, .delta): return p4nddec128v16(input, f.count, output.assumingMemoryBound(to: UInt16.self))
        case (16, .zigzag): return p4nzdec128v16(input, f.count, output.assumingMemoryBound(to: UInt16.self))
        case (16, .pfor): return p4ndec16(input, f.count, output.assumingMemoryBound(to: UInt16.self))
        case (16, .pforSIMD): return p4ndec128v16(input, f.count, output.assumingMemoryBound(to: UInt16.self))
        case (32, .delta): return p4nddec128v32(input, f.count, output.assumingMemoryBound(to: UInt32.self))
        case (32, .zigzag): return p4nzdec128v32(input, f.count, output.assumingMemoryBound(to: UInt32.self))
        case (32, .pfor): return p4ndec32(input, f.count, output.assumingMemoryBound(to: UInt32.self))
        case (32, .pforSIMD): return p4ndec128v32(input, f.count, output.assumingMemoryBound(to: UInt32.self))
        case (32, .fpx): return fpxdec32(input, f.count, output.assumingMemoryBound(to: UInt32.self), 0)
        case (64, .delta): return p4nddec64(input, f.count, output.assumingMemoryBound(to: UInt64.self))
        case (64, .zigzag): return p4nzdec64(input, f.count, output.assumingMemoryBound(to: UInt64.self))
        case (64, .pfor): return p4ndec64(input, f.count, output.assumingMemoryBound(to: UInt64.self))
        case (64, .pforSIMD): return p4ndec128v64(input, f.count, output.assumingMemoryBound(to: UInt64.self))
        case (64, .fpx): return fpxdec64(input, f.count, output.assumingMemoryBound(to: UInt64.self), 0)
        default: preconditionFailure("Unsupported fixture codec")
        }
    }

    @Test(arguments: fixtures + additionalFixtures)
    func encodingMatchesFixedBytes(_ f: Fixture) {
        let values = valueBytes(f)
        let input = UnsafeMutableRawPointer.allocate(byteCount: values.count + 64, alignment: 16)
        defer { input.deallocate() }
        input.initializeMemory(as: UInt8.self, repeating: 0, count: values.count + 64)
        values.withUnsafeBytes { input.copyMemory(from: $0.baseAddress!, byteCount: $0.count) }
        // Check both clean and reused output buffers. Only the reported bytes
        // belong to the stream; padding and scratch space are not snapshotted.
        for fill: UInt8 in [0, 0xa5] {
            var output = [UInt8](repeating: fill, count: f.count * 16 + 4096)
            let length = output.withUnsafeMutableBufferPointer { encode(f, input, $0.baseAddress!) }
            #expect(length == f.compressed.count)
            #expect(Array(output.prefix(length)) == f.compressed)
        }
    }

    @Test(arguments: fixtures + additionalFixtures)
    func decodingFixedBytes(_ f: Fixture) {
        var input = f.compressed + [UInt8](repeating: 0, count: 64)
        let expected = valueBytes(f)
        let output = UnsafeMutableRawPointer.allocate(byteCount: expected.count + 64, alignment: 16)
        defer { output.deallocate() }
        output.initializeMemory(as: UInt8.self, repeating: 0xa5, count: expected.count + 64)
        let consumed = input.withUnsafeMutableBufferPointer { decode(f, $0.baseAddress!, output) }
        #expect(consumed == f.compressed.count)
        #expect(Array(UnsafeRawBufferPointer(start: output, count: expected.count)) == expected)

        // The bounded OM decoders must accept the same historical bytes.
        if f.codec == .delta || f.codec == .zigzag || f.codec == .fpx {
            output.initializeMemory(as: UInt8.self, repeating: 0xa5, count: expected.count + 64)
            let bounded = input.withUnsafeBytes { src in
                f.codec == .fpx
                    ? om_fpx_decode(src.baseAddress, f.compressed.count, f.count, output, UInt32(f.bits))
                    : om_pfor_decode(src.baseAddress, f.compressed.count, f.count, output, UInt32(f.bits), f.codec == .zigzag)
            }
            #expect(bounded == f.compressed.count)
            #expect(Array(UnsafeRawBufferPointer(start: output, count: expected.count)) == expected)
        }
    }
}
